---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: awx-ingress
  namespace: awx
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`awx.k8s.rsletten.com`)
      kind: Rule
      services:
        - name: awx-service
          port: 80
  tls:
    certResolver: cloudflare
    secretName: awx-cert
